spring:
  application:
    name: facturacion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/facturacion_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
server:
  port: 8081
