apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: kubernetes-cosecha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # Puerto AMQP
            - containerPort: 15672 # Puerto del panel de gestión
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: kubernetes-cosecha
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP